version: "3.8"

services:
  app:
    build:
      context: "."
    container_name: ${APP_NAME}-app
    volumes:
      - ../:/var/www/html:cached
      - ./sites.conf/:/etc/apache2/sites.conf
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - 80:80
    tty: true

  mysql:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: mysqld --default-authentication-plugin=mysql_native_password --thread_stack=256K
    restart: always
    container_name: ${APP_NAME}-mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./db/:/var/db

  ############################
  # PHPMyAdmin service
  ############################
  # phpmyadmin:
  #   container_name: ${APP_NAME}-phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mysql
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOST=mysql
  #     - PMA_USER=root
  #   ports:
  #     - ${PHPMYADMIN_PORT}:80
  #   links:
  #     - mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root

  ############################
  # Maildev service
  ############################
  maildev:
    container_name: ${APP_NAME}-maildev
    image: maildev/maildev
    ports:
      - 8082:1080